name: Docker
on:
  workflow_dispatch:
  push:
    branches: [main]
env:
  ALIYUN_REGISTRY: ${{ secrets.ALIYUN_REGISTRY }}
  ALIYUN_NAME_SPACE: ${{ secrets.ALIYUN_NAME_SPACE }}
  ALIYUN_REGISTRY_USER: ${{ secrets.ALIYUN_REGISTRY_USER }}
  ALIYUN_REGISTRY_PASSWORD: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }}
jobs:
  build:
    name: Build and Push Multi - Arch Images
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    - name: Docker Setup Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Aliyun Registry
      run: docker login -u $ALIYUN_REGISTRY_USER -p $ALIYUN_REGISTRY_PASSWORD $ALIYUN_REGISTRY
    - name: Build and Push Multi - Arch Images
      run: |
        architectures=("linux/arm64" "linux/arm/v7" "linux/amd64")
        for arch in "${architectures[@]}"; do
          docker buildx build \
            --platform $arch \
            -t $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:latest \
            --push .
        done
    - name: Create Manifest List
      run: |
        docker manifest create \
          $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:latest \
          $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:latest --amend
        docker manifest push $ALIYUN_REGISTRY/$ALIYUN_NAME_SPACE/nginx:latest
